### ISSUE TITLE
feat(app): running db migration command on each new deployment

### ISSUE THREAD

**Issue by StewartJingga** [odpf/charts#28]
**Is your feature request related to a problem? Please describe.**
I want to use `app` chart for deploying my service. My service happens to have a db migration command that needs to be run before running my service. Right now `app` chart does not support a direct way to do that.

**Describe the solution you'd like**
Have a migration config and values that we can toggle and fill to create a k8s job for running db migration.
e.g.
```
# values.yaml
...
migration:
  enabled: false
  command: ~
  args:
    - migrate
```
