### ISSUE TITLE
Should the service or ingress annotations be part of the charts

### ISSUE THREAD

**Issue by bsushmith** [odpf/charts#72]
**Summary**
Should the service or ingress annotations be part of the charts, since the current values are based on our internal infra, and users can have their own different controllers?

Example:
```yaml
  service:
    annotations:
      projectcontour.io/upstream-protocol.h2c: tcp

```

https://github.com/odpf/charts/blob/main/stable/guardian/values.yaml#L33

Related discussion - https://github.com/odpf/charts/pull/66#discussion_r940912752
