### ISSUE TITLE
Support livenessProbe and readinessProbe with `exec`

### ISSUE THREAD

**Issue by mabdh** [odpf/charts#87]
In siren chart, we have 2 workers and require to use `livenessProbe` and `readinessProbe` with `exec`.

```yaml
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - ps -ef | grep siren | grep -v grep
      httpGet: null
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - ps -ef | grep siren | grep -v grep
      httpGet: null
      initialDelaySeconds: 10
      periodSeconds: 10
```

And there is already a default `httpGet` value in both probes in `charts/app`. I expect setting this as `httpGet=null` would unset the httpGet value. But turns out both probes `exec` and `httpGet` are rendered and this caused an error when doing `helm upgrade`

```bash
Error: failed to create resource: Deployment.apps "xxx" is invalid: [spec.template.spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type, spec.template.spec.containers[0].readinessProbe.httpGet: Forbidden: may not specify more than 1 handler type]
```

This is a long pending issue since helm 3. Refer [here](https://github.com/helm/helm/issues/9027).

**Solution**

In this PR, I add if-else checking in `deployment` template. If `exec` probe exists, use it only, if not use whatever the value in the `livenessProbe` or `readinessProbe`.
